# Generated by Django 4.2.6 on 2023-11-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_activity_id_alter_methodology_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='field',
        ),
        migrations.RemoveField(
            model_name='project',
            name='methodology',
        ),
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.ManyToManyField(to='map.activity'),
        ),
    ]
