### List Methodology
GET {{host}}/api/map/methodologies/
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Create Methodology
POST {{host}}/api/map/methodologies/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Methodology B",
    "description": "Methodology B"
}


### Methodology Detail
GET {{host}}/api/map/methodologies/3/
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Update Methodology
PUT {{host}}/api/map/methodologies/3/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Methodology C",
    "description": "Methodology C"
}


### Delete Methodology
DELETE {{host}}/api/map/methodologies/3/
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### List Activity
GET {{host}}/api/map/activities/
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Create Activity
POST {{host}}/api/map/activities/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Activity 1",
    "description": "Activity 1",
    "methodology_id": 1
}


### Activity Detail
GET {{host}}/api/map/activities/1/
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Update Activity
PUT {{host}}/api/map/activities/10/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Methodology C",
    "description": "Methodology C",
    "methodology_id": 1
}


### Delete Activity
DELETE {{host}}/api/map/activities/10/
Content-Type: application/json
Authorization: Bearer {{accessToken}}